/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PastoralLettersRouteImport } from './routes/pastoral-letters'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as NewsSubmitRouteImport } from './routes/news/submit'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthInitAdminRouteImport } from './routes/_auth/init-admin'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDashboardNewsRouteImport } from './routes/_app/dashboard/news'
import { Route as AppDashboardNewsIndexRouteImport } from './routes/_app/dashboard/news/index'
import { Route as AppDashboardEventsIndexRouteImport } from './routes/_app/dashboard/events/index'
import { Route as AppDashboardEventsCreateRouteImport } from './routes/_app/dashboard/events/create'

const PastoralLettersRoute = PastoralLettersRouteImport.update({
  id: '/pastoral-letters',
  path: '/pastoral-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSubmitRoute = NewsSubmitRouteImport.update({
  id: '/news/submit',
  path: '/news/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInitAdminRoute = AuthInitAdminRouteImport.update({
  id: '/_auth/init-admin',
  path: '/init-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardNewsRoute = AppDashboardNewsRouteImport.update({
  id: '/dashboard/news',
  path: '/dashboard/news',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardNewsIndexRoute = AppDashboardNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardNewsRoute,
} as any)
const AppDashboardEventsIndexRoute = AppDashboardEventsIndexRouteImport.update({
  id: '/dashboard/events/',
  path: '/dashboard/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardEventsCreateRoute =
  AppDashboardEventsCreateRouteImport.update({
    id: '/dashboard/events/create',
    path: '/dashboard/events/create',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pastoral-letters': typeof PastoralLettersRoute
  '/init-admin': typeof AuthInitAdminRoute
  '/sign-in': typeof AuthSignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/submit': typeof NewsSubmitRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/dashboard/news': typeof AppDashboardNewsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/events/create': typeof AppDashboardEventsCreateRoute
  '/dashboard/events/': typeof AppDashboardEventsIndexRoute
  '/dashboard/news/': typeof AppDashboardNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pastoral-letters': typeof PastoralLettersRoute
  '/init-admin': typeof AuthInitAdminRoute
  '/sign-in': typeof AuthSignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/submit': typeof NewsSubmitRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/events/create': typeof AppDashboardEventsCreateRoute
  '/dashboard/events': typeof AppDashboardEventsIndexRoute
  '/dashboard/news': typeof AppDashboardNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/pastoral-letters': typeof PastoralLettersRoute
  '/_auth/init-admin': typeof AuthInitAdminRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/events/$id': typeof EventsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/submit': typeof NewsSubmitRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/_app/dashboard/news': typeof AppDashboardNewsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/events/create': typeof AppDashboardEventsCreateRoute
  '/_app/dashboard/events/': typeof AppDashboardEventsIndexRoute
  '/_app/dashboard/news/': typeof AppDashboardNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pastoral-letters'
    | '/init-admin'
    | '/sign-in'
    | '/api/upload'
    | '/events/$id'
    | '/news/$slug'
    | '/news/submit'
    | '/events/'
    | '/news/'
    | '/dashboard/news'
    | '/api/auth/$'
    | '/api/media/$'
    | '/dashboard/'
    | '/dashboard/events/create'
    | '/dashboard/events/'
    | '/dashboard/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pastoral-letters'
    | '/init-admin'
    | '/sign-in'
    | '/api/upload'
    | '/events/$id'
    | '/news/$slug'
    | '/news/submit'
    | '/events'
    | '/news'
    | '/api/auth/$'
    | '/api/media/$'
    | '/dashboard'
    | '/dashboard/events/create'
    | '/dashboard/events'
    | '/dashboard/news'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/pastoral-letters'
    | '/_auth/init-admin'
    | '/_auth/sign-in'
    | '/api/upload'
    | '/events/$id'
    | '/news/$slug'
    | '/news/submit'
    | '/events/'
    | '/news/'
    | '/_app/dashboard/news'
    | '/api/auth/$'
    | '/api/media/$'
    | '/_app/dashboard/'
    | '/_app/dashboard/events/create'
    | '/_app/dashboard/events/'
    | '/_app/dashboard/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PastoralLettersRoute: typeof PastoralLettersRoute
  AuthInitAdminRoute: typeof AuthInitAdminRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ApiUploadRoute: typeof ApiUploadRoute
  EventsIdRoute: typeof EventsIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsSubmitRoute: typeof NewsSubmitRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pastoral-letters': {
      id: '/pastoral-letters'
      path: '/pastoral-letters'
      fullPath: '/pastoral-letters'
      preLoaderRoute: typeof PastoralLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/submit': {
      id: '/news/submit'
      path: '/news/submit'
      fullPath: '/news/submit'
      preLoaderRoute: typeof NewsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/init-admin': {
      id: '/_auth/init-admin'
      path: '/init-admin'
      fullPath: '/init-admin'
      preLoaderRoute: typeof AuthInitAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/news': {
      id: '/_app/dashboard/news'
      path: '/dashboard/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof AppDashboardNewsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/news/': {
      id: '/_app/dashboard/news/'
      path: '/'
      fullPath: '/dashboard/news/'
      preLoaderRoute: typeof AppDashboardNewsIndexRouteImport
      parentRoute: typeof AppDashboardNewsRoute
    }
    '/_app/dashboard/events/': {
      id: '/_app/dashboard/events/'
      path: '/dashboard/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof AppDashboardEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/events/create': {
      id: '/_app/dashboard/events/create'
      path: '/dashboard/events/create'
      fullPath: '/dashboard/events/create'
      preLoaderRoute: typeof AppDashboardEventsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppDashboardNewsRouteChildren {
  AppDashboardNewsIndexRoute: typeof AppDashboardNewsIndexRoute
}

const AppDashboardNewsRouteChildren: AppDashboardNewsRouteChildren = {
  AppDashboardNewsIndexRoute: AppDashboardNewsIndexRoute,
}

const AppDashboardNewsRouteWithChildren =
  AppDashboardNewsRoute._addFileChildren(AppDashboardNewsRouteChildren)

interface AppRouteRouteChildren {
  AppDashboardNewsRoute: typeof AppDashboardNewsRouteWithChildren
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardEventsCreateRoute: typeof AppDashboardEventsCreateRoute
  AppDashboardEventsIndexRoute: typeof AppDashboardEventsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardNewsRoute: AppDashboardNewsRouteWithChildren,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardEventsCreateRoute: AppDashboardEventsCreateRoute,
  AppDashboardEventsIndexRoute: AppDashboardEventsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PastoralLettersRoute: PastoralLettersRoute,
  AuthInitAdminRoute: AuthInitAdminRoute,
  AuthSignInRoute: AuthSignInRoute,
  ApiUploadRoute: ApiUploadRoute,
  EventsIdRoute: EventsIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsSubmitRoute: NewsSubmitRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
