/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as PastoralLettersRouteImport } from './routes/pastoral-letters'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as ChaplainContactRouteImport } from './routes/chaplain-contact'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as ProgrammesSubmitRouteImport } from './routes/programmes/submit'
import { Route as ParishesIdRouteImport } from './routes/parishes/$id'
import { Route as NewsSubmitRouteImport } from './routes/news/submit'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'
import { Route as ChaplainChatTokenRouteImport } from './routes/chaplain-chat/$token'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthInitAdminRouteImport } from './routes/_auth/init-admin'
import { Route as EventsIdIndexRouteImport } from './routes/events/$id/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as EventsIdCancelRouteImport } from './routes/events/$id/cancel'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as ApiChatUploadRouteImport } from './routes/api/chat/upload'
import { Route as ApiChatSseRouteImport } from './routes/api/chat/sse'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDashboardNewsRouteImport } from './routes/_app/dashboard/news'
import { Route as AppDashboardSubmissionPromptsIndexRouteImport } from './routes/_app/dashboard/submission-prompts/index'
import { Route as AppDashboardSettingsIndexRouteImport } from './routes/_app/dashboard/settings/index'
import { Route as AppDashboardProgrammesIndexRouteImport } from './routes/_app/dashboard/programmes/index'
import { Route as AppDashboardNewsIndexRouteImport } from './routes/_app/dashboard/news/index'
import { Route as AppDashboardMembersIndexRouteImport } from './routes/_app/dashboard/members/index'
import { Route as AppDashboardExecutiveIndexRouteImport } from './routes/_app/dashboard/executive/index'
import { Route as AppDashboardEventsIndexRouteImport } from './routes/_app/dashboard/events/index'
import { Route as AppDashboardDocumentsIndexRouteImport } from './routes/_app/dashboard/documents/index'
import { Route as AppDashboardChaplainIndexRouteImport } from './routes/_app/dashboard/chaplain/index'
import { Route as AppDashboardAdminUsersIndexRouteImport } from './routes/_app/dashboard/admin-users/index'
import { Route as AppDashboardSubmissionPromptsCreateRouteImport } from './routes/_app/dashboard/submission-prompts/create'
import { Route as AppDashboardProgrammesCreateRouteImport } from './routes/_app/dashboard/programmes/create'
import { Route as AppDashboardProgrammesIdRouteImport } from './routes/_app/dashboard/programmes/$id'
import { Route as AppDashboardNewsSubmissionsRouteImport } from './routes/_app/dashboard/news/submissions'
import { Route as AppDashboardNewsCreateRouteImport } from './routes/_app/dashboard/news/create'
import { Route as AppDashboardNewsIdRouteImport } from './routes/_app/dashboard/news/$id'
import { Route as AppDashboardEventsRegistrantsRouteImport } from './routes/_app/dashboard/events/registrants'
import { Route as AppDashboardEventsCreateRouteImport } from './routes/_app/dashboard/events/create'
import { Route as AppDashboardEventsIdRouteImport } from './routes/_app/dashboard/events/$id'
import { Route as AppDashboardDocumentsUploadRouteImport } from './routes/_app/dashboard/documents/upload'
import { Route as AppDashboardChaplainIdRouteImport } from './routes/_app/dashboard/chaplain/$id'

const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PastoralLettersRoute = PastoralLettersRouteImport.update({
  id: '/pastoral-letters',
  path: '/pastoral-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaplainContactRoute = ChaplainContactRouteImport.update({
  id: '/chaplain-contact',
  path: '/chaplain-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSubmitRoute = ProgrammesSubmitRouteImport.update({
  id: '/programmes/submit',
  path: '/programmes/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ParishesIdRoute = ParishesIdRouteImport.update({
  id: '/parishes/$id',
  path: '/parishes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSubmitRoute = NewsSubmitRouteImport.update({
  id: '/news/submit',
  path: '/news/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaplainChatTokenRoute = ChaplainChatTokenRouteImport.update({
  id: '/chaplain-chat/$token',
  path: '/chaplain-chat/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInitAdminRoute = AuthInitAdminRouteImport.update({
  id: '/_auth/init-admin',
  path: '/init-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const EventsIdCancelRoute = EventsIdCancelRouteImport.update({
  id: '/events/$id/cancel',
  path: '/events/$id/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatUploadRoute = ApiChatUploadRouteImport.update({
  id: '/api/chat/upload',
  path: '/api/chat/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSseRoute = ApiChatSseRouteImport.update({
  id: '/api/chat/sse',
  path: '/api/chat/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardNewsRoute = AppDashboardNewsRouteImport.update({
  id: '/dashboard/news',
  path: '/dashboard/news',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardSubmissionPromptsIndexRoute =
  AppDashboardSubmissionPromptsIndexRouteImport.update({
    id: '/dashboard/submission-prompts/',
    path: '/dashboard/submission-prompts/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardSettingsIndexRoute =
  AppDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardProgrammesIndexRoute =
  AppDashboardProgrammesIndexRouteImport.update({
    id: '/dashboard/programmes/',
    path: '/dashboard/programmes/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardNewsIndexRoute = AppDashboardNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardNewsRoute,
} as any)
const AppDashboardMembersIndexRoute =
  AppDashboardMembersIndexRouteImport.update({
    id: '/dashboard/members/',
    path: '/dashboard/members/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardExecutiveIndexRoute =
  AppDashboardExecutiveIndexRouteImport.update({
    id: '/dashboard/executive/',
    path: '/dashboard/executive/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardEventsIndexRoute = AppDashboardEventsIndexRouteImport.update({
  id: '/dashboard/events/',
  path: '/dashboard/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardDocumentsIndexRoute =
  AppDashboardDocumentsIndexRouteImport.update({
    id: '/dashboard/documents/',
    path: '/dashboard/documents/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardChaplainIndexRoute =
  AppDashboardChaplainIndexRouteImport.update({
    id: '/dashboard/chaplain/',
    path: '/dashboard/chaplain/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardAdminUsersIndexRoute =
  AppDashboardAdminUsersIndexRouteImport.update({
    id: '/dashboard/admin-users/',
    path: '/dashboard/admin-users/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardSubmissionPromptsCreateRoute =
  AppDashboardSubmissionPromptsCreateRouteImport.update({
    id: '/dashboard/submission-prompts/create',
    path: '/dashboard/submission-prompts/create',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardProgrammesCreateRoute =
  AppDashboardProgrammesCreateRouteImport.update({
    id: '/dashboard/programmes/create',
    path: '/dashboard/programmes/create',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardProgrammesIdRoute =
  AppDashboardProgrammesIdRouteImport.update({
    id: '/dashboard/programmes/$id',
    path: '/dashboard/programmes/$id',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardNewsSubmissionsRoute =
  AppDashboardNewsSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AppDashboardNewsRoute,
  } as any)
const AppDashboardNewsCreateRoute = AppDashboardNewsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppDashboardNewsRoute,
} as any)
const AppDashboardNewsIdRoute = AppDashboardNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardNewsRoute,
} as any)
const AppDashboardEventsRegistrantsRoute =
  AppDashboardEventsRegistrantsRouteImport.update({
    id: '/dashboard/events/registrants',
    path: '/dashboard/events/registrants',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardEventsCreateRoute =
  AppDashboardEventsCreateRouteImport.update({
    id: '/dashboard/events/create',
    path: '/dashboard/events/create',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardEventsIdRoute = AppDashboardEventsIdRouteImport.update({
  id: '/dashboard/events/$id',
  path: '/dashboard/events/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardDocumentsUploadRoute =
  AppDashboardDocumentsUploadRouteImport.update({
    id: '/dashboard/documents/upload',
    path: '/dashboard/documents/upload',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardChaplainIdRoute = AppDashboardChaplainIdRouteImport.update({
  id: '/dashboard/chaplain/$id',
  path: '/dashboard/chaplain/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chaplain-contact': typeof ChaplainContactRoute
  '/executive': typeof ExecutiveRoute
  '/pastoral-letters': typeof PastoralLettersRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/init-admin': typeof AuthInitAdminRoute
  '/api/upload': typeof ApiUploadRoute
  '/chaplain-chat/$token': typeof ChaplainChatTokenRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/submit': typeof NewsSubmitRoute
  '/parishes/$id': typeof ParishesIdRoute
  '/programmes/submit': typeof ProgrammesSubmitRoute
  '/documents/': typeof DocumentsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/dashboard/news': typeof AppDashboardNewsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/sse': typeof ApiChatSseRoute
  '/api/chat/upload': typeof ApiChatUploadRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/events/$id/cancel': typeof EventsIdCancelRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/dashboard/chaplain/$id': typeof AppDashboardChaplainIdRoute
  '/dashboard/documents/upload': typeof AppDashboardDocumentsUploadRoute
  '/dashboard/events/$id': typeof AppDashboardEventsIdRoute
  '/dashboard/events/create': typeof AppDashboardEventsCreateRoute
  '/dashboard/events/registrants': typeof AppDashboardEventsRegistrantsRoute
  '/dashboard/news/$id': typeof AppDashboardNewsIdRoute
  '/dashboard/news/create': typeof AppDashboardNewsCreateRoute
  '/dashboard/news/submissions': typeof AppDashboardNewsSubmissionsRoute
  '/dashboard/programmes/$id': typeof AppDashboardProgrammesIdRoute
  '/dashboard/programmes/create': typeof AppDashboardProgrammesCreateRoute
  '/dashboard/submission-prompts/create': typeof AppDashboardSubmissionPromptsCreateRoute
  '/dashboard/admin-users/': typeof AppDashboardAdminUsersIndexRoute
  '/dashboard/chaplain/': typeof AppDashboardChaplainIndexRoute
  '/dashboard/documents/': typeof AppDashboardDocumentsIndexRoute
  '/dashboard/events/': typeof AppDashboardEventsIndexRoute
  '/dashboard/executive/': typeof AppDashboardExecutiveIndexRoute
  '/dashboard/members/': typeof AppDashboardMembersIndexRoute
  '/dashboard/news/': typeof AppDashboardNewsIndexRoute
  '/dashboard/programmes/': typeof AppDashboardProgrammesIndexRoute
  '/dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/dashboard/submission-prompts/': typeof AppDashboardSubmissionPromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chaplain-contact': typeof ChaplainContactRoute
  '/executive': typeof ExecutiveRoute
  '/pastoral-letters': typeof PastoralLettersRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/init-admin': typeof AuthInitAdminRoute
  '/api/upload': typeof ApiUploadRoute
  '/chaplain-chat/$token': typeof ChaplainChatTokenRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/submit': typeof NewsSubmitRoute
  '/parishes/$id': typeof ParishesIdRoute
  '/programmes/submit': typeof ProgrammesSubmitRoute
  '/documents': typeof DocumentsIndexRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/sse': typeof ApiChatSseRoute
  '/api/chat/upload': typeof ApiChatUploadRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/events/$id/cancel': typeof EventsIdCancelRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/events/$id': typeof EventsIdIndexRoute
  '/dashboard/chaplain/$id': typeof AppDashboardChaplainIdRoute
  '/dashboard/documents/upload': typeof AppDashboardDocumentsUploadRoute
  '/dashboard/events/$id': typeof AppDashboardEventsIdRoute
  '/dashboard/events/create': typeof AppDashboardEventsCreateRoute
  '/dashboard/events/registrants': typeof AppDashboardEventsRegistrantsRoute
  '/dashboard/news/$id': typeof AppDashboardNewsIdRoute
  '/dashboard/news/create': typeof AppDashboardNewsCreateRoute
  '/dashboard/news/submissions': typeof AppDashboardNewsSubmissionsRoute
  '/dashboard/programmes/$id': typeof AppDashboardProgrammesIdRoute
  '/dashboard/programmes/create': typeof AppDashboardProgrammesCreateRoute
  '/dashboard/submission-prompts/create': typeof AppDashboardSubmissionPromptsCreateRoute
  '/dashboard/admin-users': typeof AppDashboardAdminUsersIndexRoute
  '/dashboard/chaplain': typeof AppDashboardChaplainIndexRoute
  '/dashboard/documents': typeof AppDashboardDocumentsIndexRoute
  '/dashboard/events': typeof AppDashboardEventsIndexRoute
  '/dashboard/executive': typeof AppDashboardExecutiveIndexRoute
  '/dashboard/members': typeof AppDashboardMembersIndexRoute
  '/dashboard/news': typeof AppDashboardNewsIndexRoute
  '/dashboard/programmes': typeof AppDashboardProgrammesIndexRoute
  '/dashboard/settings': typeof AppDashboardSettingsIndexRoute
  '/dashboard/submission-prompts': typeof AppDashboardSubmissionPromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/chaplain-contact': typeof ChaplainContactRoute
  '/executive': typeof ExecutiveRoute
  '/pastoral-letters': typeof PastoralLettersRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/_auth/init-admin': typeof AuthInitAdminRoute
  '/api/upload': typeof ApiUploadRoute
  '/chaplain-chat/$token': typeof ChaplainChatTokenRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/submit': typeof NewsSubmitRoute
  '/parishes/$id': typeof ParishesIdRoute
  '/programmes/submit': typeof ProgrammesSubmitRoute
  '/documents/': typeof DocumentsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/_app/dashboard/news': typeof AppDashboardNewsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/sse': typeof ApiChatSseRoute
  '/api/chat/upload': typeof ApiChatUploadRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/events/$id/cancel': typeof EventsIdCancelRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/_app/dashboard/chaplain/$id': typeof AppDashboardChaplainIdRoute
  '/_app/dashboard/documents/upload': typeof AppDashboardDocumentsUploadRoute
  '/_app/dashboard/events/$id': typeof AppDashboardEventsIdRoute
  '/_app/dashboard/events/create': typeof AppDashboardEventsCreateRoute
  '/_app/dashboard/events/registrants': typeof AppDashboardEventsRegistrantsRoute
  '/_app/dashboard/news/$id': typeof AppDashboardNewsIdRoute
  '/_app/dashboard/news/create': typeof AppDashboardNewsCreateRoute
  '/_app/dashboard/news/submissions': typeof AppDashboardNewsSubmissionsRoute
  '/_app/dashboard/programmes/$id': typeof AppDashboardProgrammesIdRoute
  '/_app/dashboard/programmes/create': typeof AppDashboardProgrammesCreateRoute
  '/_app/dashboard/submission-prompts/create': typeof AppDashboardSubmissionPromptsCreateRoute
  '/_app/dashboard/admin-users/': typeof AppDashboardAdminUsersIndexRoute
  '/_app/dashboard/chaplain/': typeof AppDashboardChaplainIndexRoute
  '/_app/dashboard/documents/': typeof AppDashboardDocumentsIndexRoute
  '/_app/dashboard/events/': typeof AppDashboardEventsIndexRoute
  '/_app/dashboard/executive/': typeof AppDashboardExecutiveIndexRoute
  '/_app/dashboard/members/': typeof AppDashboardMembersIndexRoute
  '/_app/dashboard/news/': typeof AppDashboardNewsIndexRoute
  '/_app/dashboard/programmes/': typeof AppDashboardProgrammesIndexRoute
  '/_app/dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/_app/dashboard/submission-prompts/': typeof AppDashboardSubmissionPromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/chaplain-contact'
    | '/executive'
    | '/pastoral-letters'
    | '/payment-callback'
    | '/init-admin'
    | '/api/upload'
    | '/chaplain-chat/$token'
    | '/dashboard/login'
    | '/news/$slug'
    | '/news/submit'
    | '/parishes/$id'
    | '/programmes/submit'
    | '/documents/'
    | '/events/'
    | '/news/'
    | '/programmes/'
    | '/dashboard/news'
    | '/api/auth/$'
    | '/api/chat/sse'
    | '/api/chat/upload'
    | '/api/media/$'
    | '/events/$id/cancel'
    | '/dashboard/'
    | '/events/$id/'
    | '/dashboard/chaplain/$id'
    | '/dashboard/documents/upload'
    | '/dashboard/events/$id'
    | '/dashboard/events/create'
    | '/dashboard/events/registrants'
    | '/dashboard/news/$id'
    | '/dashboard/news/create'
    | '/dashboard/news/submissions'
    | '/dashboard/programmes/$id'
    | '/dashboard/programmes/create'
    | '/dashboard/submission-prompts/create'
    | '/dashboard/admin-users/'
    | '/dashboard/chaplain/'
    | '/dashboard/documents/'
    | '/dashboard/events/'
    | '/dashboard/executive/'
    | '/dashboard/members/'
    | '/dashboard/news/'
    | '/dashboard/programmes/'
    | '/dashboard/settings/'
    | '/dashboard/submission-prompts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/chaplain-contact'
    | '/executive'
    | '/pastoral-letters'
    | '/payment-callback'
    | '/init-admin'
    | '/api/upload'
    | '/chaplain-chat/$token'
    | '/dashboard/login'
    | '/news/$slug'
    | '/news/submit'
    | '/parishes/$id'
    | '/programmes/submit'
    | '/documents'
    | '/events'
    | '/news'
    | '/programmes'
    | '/api/auth/$'
    | '/api/chat/sse'
    | '/api/chat/upload'
    | '/api/media/$'
    | '/events/$id/cancel'
    | '/dashboard'
    | '/events/$id'
    | '/dashboard/chaplain/$id'
    | '/dashboard/documents/upload'
    | '/dashboard/events/$id'
    | '/dashboard/events/create'
    | '/dashboard/events/registrants'
    | '/dashboard/news/$id'
    | '/dashboard/news/create'
    | '/dashboard/news/submissions'
    | '/dashboard/programmes/$id'
    | '/dashboard/programmes/create'
    | '/dashboard/submission-prompts/create'
    | '/dashboard/admin-users'
    | '/dashboard/chaplain'
    | '/dashboard/documents'
    | '/dashboard/events'
    | '/dashboard/executive'
    | '/dashboard/members'
    | '/dashboard/news'
    | '/dashboard/programmes'
    | '/dashboard/settings'
    | '/dashboard/submission-prompts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/calendar'
    | '/chaplain-contact'
    | '/executive'
    | '/pastoral-letters'
    | '/payment-callback'
    | '/_auth/init-admin'
    | '/api/upload'
    | '/chaplain-chat/$token'
    | '/dashboard/login'
    | '/news/$slug'
    | '/news/submit'
    | '/parishes/$id'
    | '/programmes/submit'
    | '/documents/'
    | '/events/'
    | '/news/'
    | '/programmes/'
    | '/_app/dashboard/news'
    | '/api/auth/$'
    | '/api/chat/sse'
    | '/api/chat/upload'
    | '/api/media/$'
    | '/events/$id/cancel'
    | '/_app/dashboard/'
    | '/events/$id/'
    | '/_app/dashboard/chaplain/$id'
    | '/_app/dashboard/documents/upload'
    | '/_app/dashboard/events/$id'
    | '/_app/dashboard/events/create'
    | '/_app/dashboard/events/registrants'
    | '/_app/dashboard/news/$id'
    | '/_app/dashboard/news/create'
    | '/_app/dashboard/news/submissions'
    | '/_app/dashboard/programmes/$id'
    | '/_app/dashboard/programmes/create'
    | '/_app/dashboard/submission-prompts/create'
    | '/_app/dashboard/admin-users/'
    | '/_app/dashboard/chaplain/'
    | '/_app/dashboard/documents/'
    | '/_app/dashboard/events/'
    | '/_app/dashboard/executive/'
    | '/_app/dashboard/members/'
    | '/_app/dashboard/news/'
    | '/_app/dashboard/programmes/'
    | '/_app/dashboard/settings/'
    | '/_app/dashboard/submission-prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ChaplainContactRoute: typeof ChaplainContactRoute
  ExecutiveRoute: typeof ExecutiveRoute
  PastoralLettersRoute: typeof PastoralLettersRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  AuthInitAdminRoute: typeof AuthInitAdminRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ChaplainChatTokenRoute: typeof ChaplainChatTokenRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsSubmitRoute: typeof NewsSubmitRoute
  ParishesIdRoute: typeof ParishesIdRoute
  ProgrammesSubmitRoute: typeof ProgrammesSubmitRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatSseRoute: typeof ApiChatSseRoute
  ApiChatUploadRoute: typeof ApiChatUploadRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  EventsIdCancelRoute: typeof EventsIdCancelRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastoral-letters': {
      id: '/pastoral-letters'
      path: '/pastoral-letters'
      fullPath: '/pastoral-letters'
      preLoaderRoute: typeof PastoralLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaplain-contact': {
      id: '/chaplain-contact'
      path: '/chaplain-contact'
      fullPath: '/chaplain-contact'
      preLoaderRoute: typeof ChaplainContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/submit': {
      id: '/programmes/submit'
      path: '/programmes/submit'
      fullPath: '/programmes/submit'
      preLoaderRoute: typeof ProgrammesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parishes/$id': {
      id: '/parishes/$id'
      path: '/parishes/$id'
      fullPath: '/parishes/$id'
      preLoaderRoute: typeof ParishesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/submit': {
      id: '/news/submit'
      path: '/news/submit'
      fullPath: '/news/submit'
      preLoaderRoute: typeof NewsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaplain-chat/$token': {
      id: '/chaplain-chat/$token'
      path: '/chaplain-chat/$token'
      fullPath: '/chaplain-chat/$token'
      preLoaderRoute: typeof ChaplainChatTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/init-admin': {
      id: '/_auth/init-admin'
      path: '/init-admin'
      fullPath: '/init-admin'
      preLoaderRoute: typeof AuthInitAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/events/$id/cancel': {
      id: '/events/$id/cancel'
      path: '/events/$id/cancel'
      fullPath: '/events/$id/cancel'
      preLoaderRoute: typeof EventsIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/upload': {
      id: '/api/chat/upload'
      path: '/api/chat/upload'
      fullPath: '/api/chat/upload'
      preLoaderRoute: typeof ApiChatUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/sse': {
      id: '/api/chat/sse'
      path: '/api/chat/sse'
      fullPath: '/api/chat/sse'
      preLoaderRoute: typeof ApiChatSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/news': {
      id: '/_app/dashboard/news'
      path: '/dashboard/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof AppDashboardNewsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/submission-prompts/': {
      id: '/_app/dashboard/submission-prompts/'
      path: '/dashboard/submission-prompts'
      fullPath: '/dashboard/submission-prompts/'
      preLoaderRoute: typeof AppDashboardSubmissionPromptsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/settings/': {
      id: '/_app/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppDashboardSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/programmes/': {
      id: '/_app/dashboard/programmes/'
      path: '/dashboard/programmes'
      fullPath: '/dashboard/programmes/'
      preLoaderRoute: typeof AppDashboardProgrammesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/news/': {
      id: '/_app/dashboard/news/'
      path: '/'
      fullPath: '/dashboard/news/'
      preLoaderRoute: typeof AppDashboardNewsIndexRouteImport
      parentRoute: typeof AppDashboardNewsRoute
    }
    '/_app/dashboard/members/': {
      id: '/_app/dashboard/members/'
      path: '/dashboard/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof AppDashboardMembersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/executive/': {
      id: '/_app/dashboard/executive/'
      path: '/dashboard/executive'
      fullPath: '/dashboard/executive/'
      preLoaderRoute: typeof AppDashboardExecutiveIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/events/': {
      id: '/_app/dashboard/events/'
      path: '/dashboard/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof AppDashboardEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/documents/': {
      id: '/_app/dashboard/documents/'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof AppDashboardDocumentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/chaplain/': {
      id: '/_app/dashboard/chaplain/'
      path: '/dashboard/chaplain'
      fullPath: '/dashboard/chaplain/'
      preLoaderRoute: typeof AppDashboardChaplainIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/admin-users/': {
      id: '/_app/dashboard/admin-users/'
      path: '/dashboard/admin-users'
      fullPath: '/dashboard/admin-users/'
      preLoaderRoute: typeof AppDashboardAdminUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/submission-prompts/create': {
      id: '/_app/dashboard/submission-prompts/create'
      path: '/dashboard/submission-prompts/create'
      fullPath: '/dashboard/submission-prompts/create'
      preLoaderRoute: typeof AppDashboardSubmissionPromptsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/programmes/create': {
      id: '/_app/dashboard/programmes/create'
      path: '/dashboard/programmes/create'
      fullPath: '/dashboard/programmes/create'
      preLoaderRoute: typeof AppDashboardProgrammesCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/programmes/$id': {
      id: '/_app/dashboard/programmes/$id'
      path: '/dashboard/programmes/$id'
      fullPath: '/dashboard/programmes/$id'
      preLoaderRoute: typeof AppDashboardProgrammesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/news/submissions': {
      id: '/_app/dashboard/news/submissions'
      path: '/submissions'
      fullPath: '/dashboard/news/submissions'
      preLoaderRoute: typeof AppDashboardNewsSubmissionsRouteImport
      parentRoute: typeof AppDashboardNewsRoute
    }
    '/_app/dashboard/news/create': {
      id: '/_app/dashboard/news/create'
      path: '/create'
      fullPath: '/dashboard/news/create'
      preLoaderRoute: typeof AppDashboardNewsCreateRouteImport
      parentRoute: typeof AppDashboardNewsRoute
    }
    '/_app/dashboard/news/$id': {
      id: '/_app/dashboard/news/$id'
      path: '/$id'
      fullPath: '/dashboard/news/$id'
      preLoaderRoute: typeof AppDashboardNewsIdRouteImport
      parentRoute: typeof AppDashboardNewsRoute
    }
    '/_app/dashboard/events/registrants': {
      id: '/_app/dashboard/events/registrants'
      path: '/dashboard/events/registrants'
      fullPath: '/dashboard/events/registrants'
      preLoaderRoute: typeof AppDashboardEventsRegistrantsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/events/create': {
      id: '/_app/dashboard/events/create'
      path: '/dashboard/events/create'
      fullPath: '/dashboard/events/create'
      preLoaderRoute: typeof AppDashboardEventsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/events/$id': {
      id: '/_app/dashboard/events/$id'
      path: '/dashboard/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof AppDashboardEventsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/documents/upload': {
      id: '/_app/dashboard/documents/upload'
      path: '/dashboard/documents/upload'
      fullPath: '/dashboard/documents/upload'
      preLoaderRoute: typeof AppDashboardDocumentsUploadRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/chaplain/$id': {
      id: '/_app/dashboard/chaplain/$id'
      path: '/dashboard/chaplain/$id'
      fullPath: '/dashboard/chaplain/$id'
      preLoaderRoute: typeof AppDashboardChaplainIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppDashboardNewsRouteChildren {
  AppDashboardNewsIdRoute: typeof AppDashboardNewsIdRoute
  AppDashboardNewsCreateRoute: typeof AppDashboardNewsCreateRoute
  AppDashboardNewsSubmissionsRoute: typeof AppDashboardNewsSubmissionsRoute
  AppDashboardNewsIndexRoute: typeof AppDashboardNewsIndexRoute
}

const AppDashboardNewsRouteChildren: AppDashboardNewsRouteChildren = {
  AppDashboardNewsIdRoute: AppDashboardNewsIdRoute,
  AppDashboardNewsCreateRoute: AppDashboardNewsCreateRoute,
  AppDashboardNewsSubmissionsRoute: AppDashboardNewsSubmissionsRoute,
  AppDashboardNewsIndexRoute: AppDashboardNewsIndexRoute,
}

const AppDashboardNewsRouteWithChildren =
  AppDashboardNewsRoute._addFileChildren(AppDashboardNewsRouteChildren)

interface AppRouteRouteChildren {
  AppDashboardNewsRoute: typeof AppDashboardNewsRouteWithChildren
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardChaplainIdRoute: typeof AppDashboardChaplainIdRoute
  AppDashboardDocumentsUploadRoute: typeof AppDashboardDocumentsUploadRoute
  AppDashboardEventsIdRoute: typeof AppDashboardEventsIdRoute
  AppDashboardEventsCreateRoute: typeof AppDashboardEventsCreateRoute
  AppDashboardEventsRegistrantsRoute: typeof AppDashboardEventsRegistrantsRoute
  AppDashboardProgrammesIdRoute: typeof AppDashboardProgrammesIdRoute
  AppDashboardProgrammesCreateRoute: typeof AppDashboardProgrammesCreateRoute
  AppDashboardSubmissionPromptsCreateRoute: typeof AppDashboardSubmissionPromptsCreateRoute
  AppDashboardAdminUsersIndexRoute: typeof AppDashboardAdminUsersIndexRoute
  AppDashboardChaplainIndexRoute: typeof AppDashboardChaplainIndexRoute
  AppDashboardDocumentsIndexRoute: typeof AppDashboardDocumentsIndexRoute
  AppDashboardEventsIndexRoute: typeof AppDashboardEventsIndexRoute
  AppDashboardExecutiveIndexRoute: typeof AppDashboardExecutiveIndexRoute
  AppDashboardMembersIndexRoute: typeof AppDashboardMembersIndexRoute
  AppDashboardProgrammesIndexRoute: typeof AppDashboardProgrammesIndexRoute
  AppDashboardSettingsIndexRoute: typeof AppDashboardSettingsIndexRoute
  AppDashboardSubmissionPromptsIndexRoute: typeof AppDashboardSubmissionPromptsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardNewsRoute: AppDashboardNewsRouteWithChildren,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardChaplainIdRoute: AppDashboardChaplainIdRoute,
  AppDashboardDocumentsUploadRoute: AppDashboardDocumentsUploadRoute,
  AppDashboardEventsIdRoute: AppDashboardEventsIdRoute,
  AppDashboardEventsCreateRoute: AppDashboardEventsCreateRoute,
  AppDashboardEventsRegistrantsRoute: AppDashboardEventsRegistrantsRoute,
  AppDashboardProgrammesIdRoute: AppDashboardProgrammesIdRoute,
  AppDashboardProgrammesCreateRoute: AppDashboardProgrammesCreateRoute,
  AppDashboardSubmissionPromptsCreateRoute:
    AppDashboardSubmissionPromptsCreateRoute,
  AppDashboardAdminUsersIndexRoute: AppDashboardAdminUsersIndexRoute,
  AppDashboardChaplainIndexRoute: AppDashboardChaplainIndexRoute,
  AppDashboardDocumentsIndexRoute: AppDashboardDocumentsIndexRoute,
  AppDashboardEventsIndexRoute: AppDashboardEventsIndexRoute,
  AppDashboardExecutiveIndexRoute: AppDashboardExecutiveIndexRoute,
  AppDashboardMembersIndexRoute: AppDashboardMembersIndexRoute,
  AppDashboardProgrammesIndexRoute: AppDashboardProgrammesIndexRoute,
  AppDashboardSettingsIndexRoute: AppDashboardSettingsIndexRoute,
  AppDashboardSubmissionPromptsIndexRoute:
    AppDashboardSubmissionPromptsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ChaplainContactRoute: ChaplainContactRoute,
  ExecutiveRoute: ExecutiveRoute,
  PastoralLettersRoute: PastoralLettersRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  AuthInitAdminRoute: AuthInitAdminRoute,
  ApiUploadRoute: ApiUploadRoute,
  ChaplainChatTokenRoute: ChaplainChatTokenRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsSubmitRoute: NewsSubmitRoute,
  ParishesIdRoute: ParishesIdRoute,
  ProgrammesSubmitRoute: ProgrammesSubmitRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatSseRoute: ApiChatSseRoute,
  ApiChatUploadRoute: ApiChatUploadRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  EventsIdCancelRoute: EventsIdCancelRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
